// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifxetmmcscffwlijpdfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeGV0bW1jc2NmZndsaWpwZGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDc3NTUsImV4cCI6MjA3NDMyMzc1NX0.2bun5QQD-WoMv9-IPNJKeTjOsv38B4EGHUwHGo5VD9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});