name: Mirror to Public

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare public subset
        shell: bash
        run: |
          set -euo pipefail
          rm -rf _public
          mkdir _public

          # Copy only safe folders (adjust if needed)
          for p in app src components pages public lib; do
            if [ -d "$p" ]; then cp -R "$p" _public/; fi
          done

          # Copy safe root files
          for f in package.json pnpm-lock.yaml yarn.lock package-lock.json README.md LICENSE PROMPTS.md; do
            [ -f "$f" ] && cp "$f" _public/ || true
          done

          # Never publish these
          rm -rf _public/.git _public/.github _public/.vercel _public/node_modules || true

          # Minimal README (avoid heredoc to keep YAML simple)
          echo "# NeedSites Public Mirror" > _public/README.md
          echo "" >> _public/README.md
          echo "This repo is an automated mirror of selected, non-sensitive parts of the private NeedSites codebase for review purposes." >> _public/README.md

          echo "Files prepared for mirror:"
          find _public -maxdepth 2 -type f | wc -l

      - name: Verify secrets
        shell: bash
        run: |
          if [ -z "${{ secrets.MIRROR_REPO }}" ]; then echo "MIRROR_REPO missing"; exit 1; fi
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then echo "MIRROR_TOKEN missing"; exit 1; fi
          echo "Target repo: ${{ secrets.MIRROR_REPO }}"

      - name: Push subset to public mirror
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.MIRROR_TOKEN }}
          repository-name: ${{ secrets.MIRROR_REPO }}
          branch: main
          folder: _public
          clean: true
          single-commit: true

